language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon
  - sudo chmod 777 /tmp/clamav
  - sudo sed -i 's#/var/lib/clamav#/tmp/clamav#g' /etc/clamav/clamd.conf
  - sudo sed -i 's#/var/lib/clamav#/tmp/clamav#g' /etc/clamav/freshclam.conf
  - sudo sh -c 'echo TCPSocket 3310 >> /etc/clamav/clamd.conf'
  - sudo freshclam
  - sudo rsync -ar /tmp/clamav/ /var/lib/clamav/
  - sudo /etc/init.d/clamav-daemon start

cache:
  directories:
    - $HOME/.composer/cache
    - /tmp/clamav

install:
  - composer install

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - vendor/bin/phpunit
